/**
 * Real-DB proof (Postgres) that the multi-agent FREE AUDIT team enriches a GROUNDED diagnosis and persists it:
 *   deterministic diagnosis (real Wobble opportunities) → 3-agent enrichment (gap → opportunity → pitch, injected
 *   deterministic provider) → ONE persisted audit row carrying the report + enrichment, grounded to the REAL
 *   opportunity service slugs (never an invented service). A provider FAILURE degrades to the deterministic report
 *   (enrichment.generated=false) — the free audit is never blocked, and the roles are each invoked once (multi-agent).
 *
 * ISOLATED + finally-cleanup. Run:  DATABASE_URL=... npx tsx src/scripts/verify-free-audit-team-db.ts
 */
import { inArray, eq } from "drizzle-orm";
import { getDb, closeDb } from "@/db";
import { audits as auditsTable, auditLogs } from "@/db/schema";
import { runFreeAuditTeam, type FreeAuditProvider } from "@/lib/free-audit/team";
import { getAudit } from "@/lib/free-audit";

async function main() {
  const db = getDb();
  const assert = (c: boolean, m: string) => { if (!c) throw new Error(`FAIL: ${m}`); console.log(`  ✓ ${m}`); };
  const uniq = `${Date.now()}`;
  const auditIds: string[] = [];

  const roleCalls: string[] = [];
  // Deterministic provider — echoes the role + grounding so we can assert the enrichment is grounded (not invented).
  const provider: FreeAuditProvider = async ({ role, grounding }) => {
    roleCalls.push(role);
    return { text: `[${role}] grounded on:\n${grounding}` };
  };
  const boomProvider: FreeAuditProvider = async () => { throw new Error("provider down"); };

  try {
    const businessName = `Acme Co ${uniq}`;
    const input = { businessName, industry: "ecommerce", signals: ["slow_response", "no_followup", "no_seo"], createdBy: "Moiz" };

    // Enriched run with the deterministic provider.
    const row = await runFreeAuditTeam(input, { runProvider: provider });
    auditIds.push(row.id);
    const stored = await getAudit(row.id);
    const report = stored!.report as unknown as { opportunities: Array<{ service: string }>; enrichment: { framedGaps: string; opportunityNarrative: string; finalPitch: string; groundedServiceSlugs: string[]; generated: boolean } };
    assert(!!stored, "the enriched audit is PERSISTED (real DB row)");
    assert(report.enrichment.generated === true, "the enrichment was GENERATED by the team");
    assert(roleCalls.length === 3 && new Set(roleCalls).size === 3, "MULTI-AGENT: three DISTINCT roles ran (gap_analyst, opportunity_writer, pitch_composer)");
    assert(report.enrichment.finalPitch.includes(input.businessName) || report.enrichment.framedGaps.includes(input.businessName) || report.enrichment.finalPitch.includes(report.opportunities[0]?.service), "the enrichment is GROUNDED in the real diagnosis (references the business / a real opportunity)");
    const realSlugs = new Set(report.opportunities.map((o) => o.service));
    assert(report.enrichment.groundedServiceSlugs.length === realSlugs.size && report.enrichment.groundedServiceSlugs.every((s) => realSlugs.has(s)), "ANTI-HALLUCINATION: the enrichment is scoped to EXACTLY the diagnosis's real service slugs (never an invented service)");
    assert((await db.select({ e: auditLogs.eventType }).from(auditLogs).where(eq(auditLogs.entityId, row.id))).some((r) => r.e === "audit.free_team_completed"), "the team run is AUDITED (audit.free_team_completed)");

    // Provider FAILURE degrades to the deterministic report — never blocked, never fabricated.
    const degraded = await runFreeAuditTeam(input, { runProvider: boomProvider });
    auditIds.push(degraded.id);
    const degradedReport = (await getAudit(degraded.id))!.report as unknown as { summary: string; enrichment: { generated: boolean; finalPitch: string } };
    assert(degradedReport.enrichment.generated === false, "a provider FAILURE degrades: enrichment.generated=false (never blocked)");
    assert(degradedReport.enrichment.finalPitch === degradedReport.summary, "the degraded audit falls back to the deterministic summary (honest, not fabricated)");

    console.log("\n✅ free-audit-team DB proof passed");
  } finally {
    if (auditIds.length) {
      await db.delete(auditLogs).where(inArray(auditLogs.entityId, auditIds));
      await db.delete(auditsTable).where(inArray(auditsTable.id, auditIds));
    }
    await closeDb();
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
